os:
  - linux
  - osx
language: generic
env:
  global:
  - SWIFT_VERSION=5.2.1

notifications:
  email:
    on_success: always
    on_failure: always

sudo: required

dist: trusty

osx_image: xcode11.3

before_install:
  - rvm install 2.6.0

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      eval "$(cat ./install-swiftenv.sh)";
      sudo apt-get install -y libcurl4-openssl-dev libblocksruntime-dev libkqueue-dev libpthread-workqueue-dev libbsd-dev;
      sudo rm /usr/bin/ld && sudo ln -s /usr/bin/ld.gold /usr/bin/ld;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      gem install slather;
    fi
  - git --version

script:
  - swift build          # build project
  - swift test           # run tests

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      swift package generate-xcodeproj;
      slather setup IBMPushNotifications.xcodeproj;
      xcodebuild -project IBMPushNotifications.xcodeproj -scheme IBMPushNotifications build;
      xcodebuild -project IBMPushNotifications.xcodeproj -scheme IBMPushNotifications -enableCodeCoverage YES test;
      slather coverage --coveralls --binary-basename IBMPushNotifications.framework -v;
    fi
